#!/bin/bash
docker ps -a -q | grep -q . && docker stop $(docker ps -a -q) || echo "no containers running"
docker ps -a -q | grep -q . && docker rm $(docker ps -a -q) || echo "no containers present"
docker volume ls -q | grep -q . && docker volume rm $(docker volume ls -q) || echo "no volumes present"
docker images -q | grep -q . && docker rmi -R $(docker images -q) || echo "no images present"
