#!/bin/bash
SCRIPT_DIR=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)
chmod 777 $SCRIPT_DIR/docker-clean
chmod 777 $SCRIPT_DIR/nuclear-docker-clean
ln $SCRIPT_DIR/docker-clean /usr/local/bin/
ln $SCRIPT_DIR/nuclear-docker-clean /usr/local/bin/
