#!/bin/bash

GITFILE=.git
PACKAGE.JSON=package.json
NODE_MODULES=node_modules

echo "checking if $GITFILE exists"
    if test -d "$GITFILE"; then
        echo "$GITFILE exists... so refreshing"
        git pull
    fi

echo "checking if $PACKAGE.JSON exits"
    if test -f "$PACKAGE.JSON"; then
        echo "package.json exists... so delete npm_modules and reinstall"
        rm -rf $NODE_MODULES
        npm install
    fi