#!/bin/bash

GITFILE=.git
PACKAGE_JSON=package.json
NODE_MODULES=node_modules

echo "checking if $GITFILE exists"
    if test -d "$GITFILE"; then
        echo "$GITFILE exists... so refreshing"
        git pull
    fi

echo "checking if $PACKAGE_JSON exits"
    if test -f "$PACKAGE_JSON"; then
        echo "package.json exists... so delete npm_modules and reinstall"
        rm -rf $NODE_MODULES
        npm audit fix --force
        npm install
    fi