#!/bin/bash
export NVM_DIR=$HOME/.nvm;
source $NVM_DIR/nvm.sh;

sudo upgrade-apt

nvm install node

for folder in ~/code/*/
    do
        (echo $folder)
        (cd "$folder" && node-repo-refresh)
    done