#!/bin/bash
upgrade-apt
export NVM_DIR=$HOME/.nvm;
source $NVM_DIR/nvm.sh;
nvm install node
npm i -g npm
cd ~/code/docker-clean
git-sync
cd -
# change below for current projects
refresh-code-folder $HOME/code/rewardapp