#!/bin/bash

upgrade-apt

node_stuff() {
    export NVM_DIR=$HOME/.nvm
    source $NVM_DIR/nvm.sh
    nvm install node
    npm i -g npm
    cd ~/code/docker-clean
    git-sync
    cd -
    # change below for current projects
    refresh-code-folder $HOME/code/rewardapp
}

if [ -n "$SUDO_USER" ]; then
    echo "If this script is run as sudo then the nodeJS updates aren't performed"
else
    node_stuff
fi
